# Generated by Django 4.2.5 on 2023-10-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='numFaltas_frequencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='periodoSem_turma',
            field=models.CharField(max_length=100),
        ),
    ]
